#!/usr/bin/env bash

# Build all browser distributions inside `dist/` directory. Must be run from
# the repository's root.

set -o nounset
set -o errexit
set -o pipefail
shopt -s nullglob

preamble="/* avsc $(jq -r .version <package.json) -- $(date) */"
mkdir -p dist
for fpath in etc/browser/*.js; do
  filename="$(basename "$fpath")"
  filename="${filename%.*}"
  browserify --standalone avro "$fpath" | uglifyjs --preamble "$preamble" -o "dist/$filename.js"
  browserify --standalone avro "$fpath" | uglifyjs --preamble "$preamble" -c -m -o "dist/$filename.min.js"
  gzip -9 -f -k "dist/$filename.min.js"
done
