#!/usr/bin/env node

'use strict';

/**
 * Get various performance rates.
 *
 * Usage:
 *
 *   ./perf [-w] SCHEMA ...
 *
 * Options:
 *
 *   -w     Use wrapped unions.
 *
 */

let avro = require('../../lib'),
    Benchmark = require('benchmark'),
    path = require('path');


let paths = process.argv.slice(2);
let index = paths.indexOf('-w');
let wrap = false;
if (~index) {
  paths.splice(index, 1);
  wrap = true;
}

// Number of random values to generate to try per schema. This is mostly to
// reduce the variability introduced by unions (which can greatly affect
// serialization speed).
let NUM_VALUES = 1000;

function maybeGC() {
  try {
    global.gc();
  } catch (err) {
    // GC not exposed
  }
}

// Header formatting is done according to GitHub flavored Markdown.
console.log(['fromBuffer', 'toBuffer', 'isValid ', '(ops/sec)'].join('\t| '));
console.log(['---------:', '-------:', '------: ', '---------'].join('\t| '));

paths.forEach((fpath) => {
  let type = avro.parse(fpath, {wrapUnions: wrap});
  let values = [];
  let bufs = [];

  for (let i = 0, l = NUM_VALUES; i < l; i++) {
    let val = type.random();
    values.push(val);
    bufs.push(type.toBuffer(val));
  }

  let stats = [];
  let bench = new Benchmark().on('complete', function () {
    let s = '' + (NUM_VALUES * this.hz | 0);
    s = s.replace(/(?=(?:\d{3})+$)(?!\b)/g, ',');
    s = (s + '            ').slice(0, 12);
    stats.push(s);
  });

  maybeGC();
  bench.clone({fn: function () {
    for (let i = 0, l = NUM_VALUES; i < l; i++) {
      let val = type.fromBuffer(bufs[i]);
      if (val.$) {
        throw new Error();
      }
    }
  }}).run();

  maybeGC();
  bench.clone({fn: function () {
    for (let i = 0, l = NUM_VALUES; i < l; i++) {
      let buf = type.toBuffer(values[i]);
      if (!buf.length) {
        throw new Error();
      }
    }
  }}).run();

  maybeGC();
  bench.clone({fn: function () {
    for (let i = 0, l = NUM_VALUES; i < l; i++) {
      if (!type.isValid(values[i])) {
        throw new Error();
      }
    }
  }}).run();

  stats.push(path.basename(fpath));
  console.log(stats.join('\t| '));
});
