#!/usr/bin/env node

/* jshint esversion: 8, node: true */

'use strict';

/**
 * Script to determine whether a package can be run on the current node version.
 *
 * Usage: check-engine ./path/to/package/
 *
 * The command will exit with code 0 if the package is compatible and 1
 * otherwise.
 */

const {checkEngine} = require('npm-install-checks');
const path = require('path');

const dpath = process.argv[2];
if (!dpath) {
  throw new Error('missing package path');
}

const target = require(path.resolve(path.join(dpath, 'package.json')));
checkEngine(target, '', process.version, false, true, (err) => {
  process.exit(err ? 1 : 0);
});
