#!/usr/bin/env bash

# Install all sub-packages.
#
# Usage:
#   install-packages

set -o nounset
set -o errexit
set -o pipefail
shopt -s nullglob

__dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

fail() {
  echo "$1" >&2 && exit 2
}

# Checks whether a package is compatible with the current node version.
#
# Usage: supported_engine path/to/package
#
# The function will return 0 if the engine is supported and 1 otherwise. The
# package directory should contain a `package.json` with its `engines.node`
# field set to a "greater than" value (e.g. `>=7`).
supported_engine() {
  local active="$(node --version | tr -cd '.0-9')"
  local requirement="$(jq -r <"$1/package.json" .engines.node)"
  if [[ ! $requirement =~ ^\>=[0-9.]+$ ]]; then
    fail "unsupported requirement: $requirement"
  fi
  local required="${requirement:2}" # Strip leading `>=`.
  local oldest="$(echo -e "$active\n$required" | sort -ruV | tail -n +2)"
  [[ $oldest == $active ]] && return 1 || return 0
}

main() {
  echo 'Installing all packages...'
  cd "$__dirname/../packages"
  for dname in *; do
    if supported_engine "$dname"; then
      (
        echo "Installing $dname."
        cd "$dname"
        npm install
        # Versions of node <10 don't support the latest mocha.
        node -e 'import(".").catch(() => {});' 2>/dev/null || npm i mocha@~7.1.0
        # Versions of node <8 require even older dependencies.
        node -e 'const a = {}; const b = {...a};' 2>/dev/null || npm i mocha@~3.5.3 tmp@~0.0.33
      )
    else
      echo "Skipping $dname, it requires a different engine."
    fi
  done
  echo 'Done installing packages.'
}

main "$@"
